### ISSUE TITLE
mangarock can't show chapter

### ISSUE THREAD

**Issue by hoangvn9x** [Ooggle/MangaRock-API#1]
https://api.mangarockhd.com/query/web401/pages?oid=mrs-chapter-200260585

Today, when I use the api, I get this error : "{"code":0,"data":[]}"

Do you know how to fix it?

**Comment by Ooggle** [comment]
Unfortunaly, since few days, you cannot get pages anymore with this web request. The payload formated api still work but i neeb to find the end point and the formation of the payload. Please be aware that this documentation is still being written and new things will show up later.

PS: i'll update the web chapter request as outdated
